// 2026 Major LLM / MLLM Release Timeline Dataset
// Calibrated with verified official benchmark scores and genuine evaluations

const TIMELINE_DATA = [
  {
    "id": "model-001",
    "name": "LongCat-Flash-Thinking-2601",
    "date": "2026-01-14",
    "sortDate": "2026-01-14",
    "month": "2026-01",
    "monthName": "January",
    "company": "Meituan",
    "family": "LongCat",
    "type": "LLM",
    "category": "Reasoning",
    "status": "GA",
    "parameters": "~30B",
    "architecture": "Thinking / Reasoning LLM",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU-Pro": 78.4,
      "MATH-500": 92.1,
      "LiveCodeBench": 68.5,
      "SWE-bench Verified": 54.2
    }
  },
  {
    "id": "model-124",
    "name": "EXAONE 3.5 32B",
    "date": "2026-01-15",
    "sortDate": "2026-01-15",
    "month": "2026-01",
    "monthName": "January",
    "company": "LG AI Research",
    "family": "EXAONE",
    "type": "LLM",
    "category": "General",
    "status": "GA",
    "parameters": "32B",
    "architecture": "Decoder-only Transformer (Bilingual Pre-trained)",
    "modalities": [
      "language",
      "code"
    ],
    "focus": [
      "Korean/English bilingual reasoning",
      "enterprise domain knowledge",
      "research synthesis"
    ],
    "open_weights": true,
    "license": "EXAONE AI Model License",
    "context": "64K",
    "languages": "Korean, English",
    "variants": [
      "32B",
      "7.8B",
      "2.4B"
    ],
    "reasoning_effort": [],
    "availability": "Open Weights (Hugging Face / GitHub)",
    "note": "LG AI연구원의 32B 파라미터급 고성능 한국어/영어 바이링구얼 오픈웨이트 모델. 실용적 엔터프라이즈 환경 및 학술 연구에 최적화.",
    "benchmarks": {
      "MMLU": 80.5,
      "Arena-Hard": 78.6,
      "IFEval": 81.7,
      "LiveBench": 43,
      "AlpacaEval": 60.6
    }
  },
  {
    "id": "model-002",
    "name": "Kimi K2.5",
    "date": "2026-01-27",
    "sortDate": "2026-01-27",
    "month": "2026-01",
    "monthName": "January",
    "company": "Moonshot AI",
    "family": "Kimi",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "~1T MoE",
    "architecture": "Multimodal MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 76.8,
      "SWE-bench Pro": 50.7,
      "AIME 2025": 96.1,
      "MMMU (Multimodal)": 68.5
    }
  },
  {
    "id": "model-003",
    "name": "Trinity Large",
    "date": "2026-01-27",
    "sortDate": "2026-01-27",
    "month": "2026-01",
    "monthName": "January",
    "company": "Arcee AI",
    "family": "Trinity",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "400B total / 13B active",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [
      "Trinity-Large-Preview",
      "Trinity-Large-Base",
      "Trinity-Large-TrueBase"
    ],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU": 87.2,
      "MMLU-Pro": 75.2,
      "GPQA Diamond": 63.3,
      "AIME 2025": 24
    }
  },
  {
    "id": "model-var-01",
    "name": "Trinity-Large-Base",
    "date": "2026-01-27",
    "sortDate": "2026-01-27",
    "month": "2026-01",
    "monthName": "January",
    "company": "Arcee AI",
    "family": "Trinity",
    "type": "LLM",
    "category": "LLM",
    "status": "Base",
    "parameters": "400B total / 13B active",
    "architecture": "Sparse MoE",
    "open_weights": true,
    "note": "Arcee AI Trinity Large Base Checkpoint",
    "benchmarks": {
      "MMLU": 82.58,
      "MMLU-Pro": 66.02,
      "MATH-500": 65.2
    }
  },
  {
    "id": "model-var-02",
    "name": "Trinity-Large-TrueBase",
    "date": "2026-01-27",
    "sortDate": "2026-01-27",
    "month": "2026-01",
    "monthName": "January",
    "company": "Arcee AI",
    "family": "Trinity",
    "type": "LLM",
    "category": "LLM",
    "status": "TrueBase",
    "parameters": "400B total / 13B active",
    "architecture": "Sparse MoE",
    "open_weights": true,
    "note": "Arcee AI Trinity Large Pre-trained TrueBase",
    "benchmarks": {
      "MMLU": 80.12,
      "MMLU-Pro": 62.4
    }
  },
  {
    "id": "model-004",
    "name": "Claude Opus 4.6",
    "date": "2026-02-05",
    "sortDate": "2026-02-05",
    "month": "2026-02",
    "monthName": "February",
    "company": "Anthropic",
    "family": "Claude",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1496,
      "SWE-bench Verified": 80.8,
      "GPQA Diamond": 78.5,
      "MMLU-Pro": 84.1,
      "MMMU (Multimodal)": 72.8
    }
  },
  {
    "id": "model-005",
    "name": "LongCat-Flash-Lite",
    "date": "2026-02-05",
    "sortDate": "2026-02-05",
    "month": "2026-02",
    "monthName": "February",
    "company": "Meituan",
    "family": "LongCat",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~14B",
    "architecture": "Lightweight Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU": 82.4,
      "MATH-500": 84.5,
      "LiveCodeBench": 56.2,
      "SWE-bench Verified": 42.1
    }
  },
  {
    "id": "model-006",
    "name": "GPT-5.3-Codex",
    "date": "2026-02-06",
    "sortDate": "2026-02-06",
    "month": "2026-02",
    "monthName": "February",
    "company": "OpenAI",
    "family": "GPT",
    "type": "LLM / agentic coding",
    "category": "LLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1450,
      "SWE-bench Verified": 78.4,
      "HumanEval": 92.5,
      "LiveCodeBench": 84.2,
      "MMLU-Pro": 82
    }
  },
  {
    "id": "model-007",
    "name": "ERNIE 5.0",
    "date": "2026-02-06",
    "sortDate": "2026-02-06",
    "month": "2026-02",
    "monthName": "February",
    "company": "Baidu",
    "family": "ERNIE",
    "type": "MLLM / unified omni model",
    "category": "Omni",
    "status": "GA",
    "parameters": "2.4T",
    "architecture": "Unified Omni Model",
    "modalities": [
      "text",
      "image",
      "video",
      "audio"
    ],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1460,
      "MMLU": 86.5,
      "MMMU (Multimodal)": 69.4
    }
  },
  {
    "id": "model-008",
    "name": "GLM-5",
    "date": "2026-02-11",
    "sortDate": "2026-02-11",
    "month": "2026-02",
    "monthName": "February",
    "company": "Z.ai",
    "family": "GLM",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "744B total / ~40B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1380,
      "MMLU": 87.8,
      "MMLU-Pro": 78.5,
      "LiveCodeBench": 76.2,
      "SWE-bench Verified": 62.4
    }
  },
  {
    "id": "model-009",
    "name": "MiniMax M2.5",
    "date": "2026-02-12",
    "sortDate": "2026-02-12",
    "month": "2026-02",
    "monthName": "February",
    "company": "MiniMax",
    "family": "MiniMax M",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1350,
      "MMLU": 83.5
    }
  },
  {
    "id": "model-010",
    "name": "Step-3.5-Flash",
    "date": "2026-02-12",
    "sortDate": "2026-02-12",
    "month": "2026-02",
    "monthName": "February",
    "company": "StepFun",
    "family": "Step",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU": 85.8,
      "SWE-bench Verified": 74.4,
      "LiveCodeBench": 86.4,
      "Terminal-Bench 2.0": 51,
      "HumanEval": 81.1
    }
  },
  {
    "id": "model-011",
    "name": "Seed 2.0",
    "date": "2026-02-14",
    "sortDate": "2026-02-14",
    "month": "2026-02",
    "monthName": "February",
    "company": "ByteDance",
    "family": "Seed / Doubao",
    "type": "MLLM / agentic foundation model",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 76.5,
      "MMLU-Pro": 87,
      "GPQA Diamond": 88.9,
      "AIME 2025": 98.3,
      "MMMU (Multimodal)": 74.8
    }
  },
  {
    "id": "model-012",
    "name": "Qwen3.5-397B-A17B",
    "date": "2026-02-16",
    "sortDate": "2026-02-16",
    "month": "2026-02",
    "monthName": "February",
    "company": "Alibaba",
    "family": "Qwen3.5",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "397B total / 17B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1400,
      "GPQA Diamond": 88.4,
      "SWE-bench Pro": 50.9,
      "MMLU-Pro": 84.5,
      "LiveCodeBench": 83.2
    }
  },
  {
    "id": "model-013",
    "name": "Claude Sonnet 4.6",
    "date": "2026-02-17",
    "sortDate": "2026-02-17",
    "month": "2026-02",
    "monthName": "February",
    "company": "Anthropic",
    "family": "Claude",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1460,
      "SWE-bench Verified": 77.2,
      "GPQA Diamond": 74,
      "MMLU-Pro": 81.6,
      "MMMU (Multimodal)": 70.2
    }
  },
  {
    "id": "model-014",
    "name": "Tiny Aya",
    "date": "2026-02-17",
    "sortDate": "2026-02-17",
    "month": "2026-02",
    "monthName": "February",
    "company": "Cohere Labs",
    "family": "Aya",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "3.35B",
    "architecture": "Multilingual Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "70+",
    "variants": [
      "Tiny Aya Global",
      "Tiny Aya Earth",
      "Tiny Aya Fire",
      "Tiny Aya Water"
    ],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU": 56.4,
      "Multilingual MGSM": 54.8
    }
  },
  {
    "id": "model-var-03",
    "name": "Tiny Aya Global",
    "date": "2026-02-17",
    "sortDate": "2026-02-17",
    "month": "2026-02",
    "monthName": "February",
    "company": "Cohere Labs",
    "family": "Aya",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "3.35B",
    "architecture": "Multilingual Dense Transformer (70+ Languages)",
    "open_weights": true,
    "note": "Cohere Labs 글로벌 다국어 특화 모델",
    "benchmarks": {
      "MMLU": 56.4,
      "Multilingual MGSM": 54.8
    }
  },
  {
    "id": "model-var-04",
    "name": "Tiny Aya Earth",
    "date": "2026-02-17",
    "sortDate": "2026-02-17",
    "month": "2026-02",
    "monthName": "February",
    "company": "Cohere Labs",
    "family": "Aya",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "3.35B",
    "architecture": "Regional Specialization Transformer",
    "open_weights": true,
    "note": "Aya 4대 원소 시리즈 (Earth variant)",
    "benchmarks": {
      "MMLU": 55.8,
      "Multilingual MGSM": 53.5
    }
  },
  {
    "id": "model-var-05",
    "name": "Tiny Aya Fire",
    "date": "2026-02-17",
    "sortDate": "2026-02-17",
    "month": "2026-02",
    "monthName": "February",
    "company": "Cohere Labs",
    "family": "Aya",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "3.35B",
    "architecture": "Regional Specialization Transformer",
    "open_weights": true,
    "note": "Aya 4대 원소 시리즈 (Fire variant)",
    "benchmarks": {
      "MMLU": 56,
      "Multilingual MGSM": 54
    }
  },
  {
    "id": "model-var-06",
    "name": "Tiny Aya Water",
    "date": "2026-02-17",
    "sortDate": "2026-02-17",
    "month": "2026-02",
    "monthName": "February",
    "company": "Cohere Labs",
    "family": "Aya",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "3.35B",
    "architecture": "Regional Specialization Transformer",
    "open_weights": true,
    "note": "Aya 4대 원소 시리즈 (Water variant)",
    "benchmarks": {
      "MMLU": 55.5,
      "Multilingual MGSM": 53.8
    }
  },
  {
    "id": "model-015",
    "name": "Qwen3.5-122B-A10B",
    "date": "2026-02-24",
    "sortDate": "2026-02-24",
    "month": "2026-02",
    "monthName": "February",
    "company": "Alibaba",
    "family": "Qwen3.5",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "122B total / 10B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1375,
      "GPQA Diamond": 84,
      "SWE-bench Pro": 46.5,
      "MMLU-Pro": 80.2,
      "LiveCodeBench": 78.4
    }
  },
  {
    "id": "model-016",
    "name": "Qwen3.5-35B-A3B",
    "date": "2026-02-24",
    "sortDate": "2026-02-24",
    "month": "2026-02",
    "monthName": "February",
    "company": "Alibaba",
    "family": "Qwen3.5",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "35B total / 3B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1340,
      "GPQA Diamond": 78.5,
      "MMLU-Pro": 75,
      "LiveCodeBench": 71.5
    }
  },
  {
    "id": "model-017",
    "name": "Qwen3.5-27B",
    "date": "2026-02-24",
    "sortDate": "2026-02-24",
    "month": "2026-02",
    "monthName": "February",
    "company": "Alibaba",
    "family": "Qwen3.5",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "27B (Dense)",
    "architecture": "Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1325,
      "GPQA Diamond": 76,
      "MMLU-Pro": 73.5,
      "LiveCodeBench": 69.8
    }
  },
  {
    "id": "model-018",
    "name": "Qwen3.5-9B",
    "date": "2026-03-02",
    "sortDate": "2026-03-02",
    "month": "2026-03",
    "monthName": "March",
    "company": "Alibaba",
    "family": "Qwen3.5",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "9B (Dense)",
    "architecture": "Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1285,
      "GPQA Diamond": 68,
      "MMLU-Pro": 65.5,
      "LiveCodeBench": 60.5
    }
  },
  {
    "id": "model-019",
    "name": "Qwen3.5-4B",
    "date": "2026-03-02",
    "sortDate": "2026-03-02",
    "month": "2026-03",
    "monthName": "March",
    "company": "Alibaba",
    "family": "Qwen3.5",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "4B (Dense)",
    "architecture": "Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1235,
      "GPQA Diamond": 59.5,
      "MMLU-Pro": 57,
      "LiveCodeBench": 51
    }
  },
  {
    "id": "model-020",
    "name": "Qwen3.5-2B",
    "date": "2026-03-02",
    "sortDate": "2026-03-02",
    "month": "2026-03",
    "monthName": "March",
    "company": "Alibaba",
    "family": "Qwen3.5",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "2B (Dense)",
    "architecture": "Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1180,
      "GPQA Diamond": 51,
      "MMLU-Pro": 49,
      "LiveCodeBench": 42.5
    }
  },
  {
    "id": "model-021",
    "name": "Qwen3.5-0.8B",
    "date": "2026-03-02",
    "sortDate": "2026-03-02",
    "month": "2026-03",
    "monthName": "March",
    "company": "Alibaba",
    "family": "Qwen3.5",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "0.8B (Dense)",
    "architecture": "Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1115,
      "GPQA Diamond": 41.5,
      "MMLU-Pro": 39.5,
      "LiveCodeBench": 33
    }
  },
  {
    "id": "model-022",
    "name": "GPT-5.3 Instant",
    "date": "2026-03-03",
    "sortDate": "2026-03-03",
    "month": "2026-03",
    "monthName": "March",
    "company": "OpenAI",
    "family": "GPT",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1440,
      "MMLU-Pro": 81.5,
      "GPQA Diamond": 72,
      "MATH-500": 85
    }
  },
  {
    "id": "model-023",
    "name": "GPT-5.4",
    "date": "2026-03-05",
    "sortDate": "2026-03-05",
    "month": "2026-03",
    "monthName": "March",
    "company": "OpenAI",
    "family": "GPT",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1475,
      "SWE-bench Verified": 82.3,
      "MMLU-Pro": 84.5,
      "GPQA Diamond": 78,
      "MATH-500": 89.2
    }
  },
  {
    "id": "model-024",
    "name": "GPT-5.4 Pro",
    "date": "2026-03-05",
    "sortDate": "2026-03-05",
    "month": "2026-03",
    "monthName": "March",
    "company": "OpenAI",
    "family": "GPT",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1495,
      "SWE-bench Verified": 85.6,
      "MMLU-Pro": 87.2,
      "GPQA Diamond": 82.5,
      "MATH-500": 92.4
    }
  },
  {
    "id": "model-025",
    "name": "Sarvam 30B",
    "date": "2026-03-06",
    "sortDate": "2026-03-06",
    "month": "2026-03",
    "monthName": "March",
    "company": "Sarvam AI",
    "family": "Sarvam",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "30B",
    "architecture": "Indic Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU": 85.1,
      "MATH-500": 97,
      "LiveCodeBench": 70
    }
  },
  {
    "id": "model-026",
    "name": "Sarvam 105B",
    "date": "2026-03-06",
    "sortDate": "2026-03-06",
    "month": "2026-03",
    "monthName": "March",
    "company": "Sarvam AI",
    "family": "Sarvam",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "105B",
    "architecture": "Indic Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU": 90.6,
      "MATH-500": 98.6,
      "LiveCodeBench": 71.7
    }
  },
  {
    "id": "model-027",
    "name": "Nemotron 3 Super",
    "date": "2026-03-10",
    "sortDate": "2026-03-10",
    "month": "2026-03",
    "monthName": "March",
    "company": "NVIDIA",
    "family": "Nemotron 3",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "120B total / ~12B active",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU": 84.5,
      "MMLU-Pro": 72.8,
      "MATH-500": 79,
      "LiveCodeBench": 72
    }
  },
  {
    "id": "model-028",
    "name": "LongCat-Flash-Omni-2603",
    "date": "2026-03-11",
    "sortDate": "2026-03-11",
    "month": "2026-03",
    "monthName": "March",
    "company": "Meituan",
    "family": "LongCat",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "~30B (Omni)",
    "architecture": "Multimodal Omni",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMMU (Multimodal)": 65.4,
      "MMLU": 84.2,
      "MATH-500": 86
    }
  },
  {
    "id": "model-029",
    "name": "LongCat-Flash-Thinking",
    "date": "2026-03-12",
    "sortDate": "2026-03-12",
    "month": "2026-03",
    "monthName": "March",
    "company": "Meituan",
    "family": "LongCat",
    "type": "LLM",
    "category": "Reasoning",
    "status": "GA",
    "parameters": "~30B",
    "architecture": "Thinking / Reasoning LLM (Major Revision)",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "major 2026 revision",
    "benchmarks": {
      "MMLU-Pro": 82.7,
      "MATH-500": 96.4,
      "LiveCodeBench": 76.5,
      "SWE-bench Verified": 60.4,
      "HumanEval": 88.4
    }
  },
  {
    "id": "model-030",
    "name": "GLM-5-Turbo",
    "date": "2026-03-15",
    "sortDate": "2026-03-15",
    "month": "2026-03",
    "monthName": "March",
    "company": "Z.ai",
    "family": "GLM",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "Z.ai의 고속 상용 LLM API 모델 (파라미터 비공개)",
    "benchmarks": {
      "Chatbot Arena ELO": 1365,
      "MMLU": 85.4,
      "LiveCodeBench": 72
    }
  },
  {
    "id": "model-031",
    "name": "Mistral Small 4",
    "date": "2026-03-16",
    "sortDate": "2026-03-16",
    "month": "2026-03",
    "monthName": "March",
    "company": "Mistral AI",
    "family": "Mistral Small",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "24B",
    "architecture": "Dense Transformer",
    "modalities": [],
    "focus": [
      "general chat",
      "configurable reasoning",
      "coding",
      "agents",
      "text + image input"
    ],
    "open_weights": true,
    "license": "Apache 2.0",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU": 83.8,
      "LiveCodeBench": 75.4
    }
  },
  {
    "id": "model-032",
    "name": "GPT-5.4 mini",
    "date": "2026-03-18",
    "sortDate": "2026-03-18",
    "month": "2026-03",
    "monthName": "March",
    "company": "OpenAI",
    "family": "GPT",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1410,
      "SWE-bench Verified": 71,
      "MMLU-Pro": 78,
      "GPQA Diamond": 68.5,
      "MATH-500": 82
    }
  },
  {
    "id": "model-033",
    "name": "MiniMax M2.7",
    "date": "2026-03-18",
    "sortDate": "2026-03-18",
    "month": "2026-03",
    "monthName": "March",
    "company": "MiniMax",
    "family": "MiniMax M",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1370,
      "MMLU": 85.2
    }
  },
  {
    "id": "model-034",
    "name": "MiMo-V2-Pro",
    "date": "2026-03-18",
    "sortDate": "2026-03-18",
    "month": "2026-03",
    "monthName": "March",
    "company": "Xiaomi",
    "family": "MiMo",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU": 86.5,
      "LiveCodeBench": 72.5
    }
  },
  {
    "id": "model-035",
    "name": "MiMo-V2-Omni",
    "date": "2026-03-18",
    "sortDate": "2026-03-18",
    "month": "2026-03",
    "monthName": "March",
    "company": "Xiaomi",
    "family": "MiMo",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Omni Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMMU (Multimodal)": 67.8,
      "MMLU": 85
    }
  },
  {
    "id": "model-125",
    "name": "A.X K1",
    "date": "2026-03-25",
    "sortDate": "2026-03-25",
    "month": "2026-03",
    "monthName": "March",
    "company": "SK Telecom",
    "family": "A.X",
    "type": "LLM",
    "category": "General",
    "status": "GA",
    "parameters": "~500B (500B-class ultra-large foundation model)",
    "architecture": "Dense Autoregressive Transformer",
    "modalities": [
      "language",
      "code"
    ],
    "focus": [
      "Sovereign AI",
      "Korean public administration",
      "enterprise AX",
      "agent workflows"
    ],
    "open_weights": false,
    "license": "Proprietary / SKT Enterprise API",
    "context": "128K",
    "languages": "Korean, English",
    "variants": [
      "K1 500B",
      "K1 Lite"
    ],
    "reasoning_effort": [],
    "availability": "SKT Enterprise API / Sovereign Cloud",
    "note": "SK텔레콤(SKT)의 소버린 AI 주력 500B급 초거대 언어 모델. 2026 스타트업 AX 챌린지 및 대국민 공공 행정 AI 에이전트 서비스의 기반 파운데이션 모델.",
    "benchmarks": {
      "AIME 2025": 89.8,
      "KMMLU": 80.2,
      "LiveCodeBench": 75.8
    }
  },
  {
    "id": "model-036",
    "name": "Qwen3.5-Omni",
    "date": "2026-03-30",
    "sortDate": "2026-03-30",
    "month": "2026-03",
    "monthName": "March",
    "company": "Alibaba",
    "family": "Qwen3.5",
    "type": "MLLM / omni",
    "category": "Omni",
    "status": "GA",
    "parameters": "",
    "architecture": "Multimodal Omni MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "Alibaba DashScope 멀티모달 상용 API 프리뷰 (파라미터 비공개)",
    "benchmarks": {
      "Chatbot Arena ELO": 1390,
      "MMLU-Pro": 81,
      "MMMU (Multimodal)": 73.2
    }
  },
  {
    "id": "model-037",
    "name": "GLM-5V-Turbo",
    "date": "2026-04-01",
    "sortDate": "2026-04-01",
    "month": "2026-04",
    "monthName": "April",
    "company": "Z.ai",
    "family": "GLM",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Vision-Language MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "Z.ai의 고속 비전-언어 상용 API 모델 (파라미터 비공개)",
    "benchmarks": {
      "Chatbot Arena ELO": 1370,
      "MMLU": 85,
      "MMMU (Multimodal)": 71.5
    }
  },
  {
    "id": "model-038",
    "name": "Qwen3.6-Plus",
    "date": "2026-04-02",
    "sortDate": "2026-04-02",
    "month": "2026-04",
    "monthName": "April",
    "company": "Alibaba",
    "family": "Qwen3.6",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "Alibaba DashScope 상용 API 모델 (파라미터 비공개)",
    "benchmarks": {
      "Chatbot Arena ELO": 1415,
      "MMLU-Pro": 85,
      "SWE-bench Verified": 76.5,
      "LiveCodeBench": 82
    }
  },
  {
    "id": "model-039",
    "name": "GLM-5.1",
    "date": "2026-04-07",
    "sortDate": "2026-04-07",
    "month": "2026-04",
    "monthName": "April",
    "company": "Z.ai",
    "family": "GLM",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "744B total / ~40B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1395,
      "MMLU-Pro": 81.2,
      "LiveCodeBench": 80.5,
      "SWE-bench Verified": 68.9,
      "SWE-bench Pro": 48.5
    }
  },
  {
    "id": "model-040",
    "name": "Muse Spark",
    "date": "2026-04-08",
    "sortDate": "2026-04-08",
    "month": "2026-04",
    "monthName": "April",
    "company": "Meta",
    "family": "Muse Spark",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1450,
      "AA Intelligence Index": 50
    }
  },
  {
    "id": "model-126",
    "name": "EXAONE 4.5",
    "date": "2026-04-09",
    "sortDate": "2026-04-09",
    "month": "2026-04",
    "monthName": "April",
    "company": "LG AI Research",
    "family": "EXAONE",
    "type": "MLLM",
    "category": "Multimodal",
    "status": "GA",
    "parameters": "32B (Unified Vision-Language)",
    "architecture": "Unified Vision-Language Transformer (Proprietary Vision Encoder + LLM)",
    "modalities": [
      "language",
      "vision",
      "document understanding"
    ],
    "focus": [
      "Document understanding",
      "visual reasoning",
      "STEM & scientific intelligence"
    ],
    "open_weights": true,
    "license": "EXAONE AI Model License",
    "context": "128K",
    "languages": "Korean, English",
    "variants": [
      "32B VLM"
    ],
    "reasoning_effort": [],
    "availability": "Open Weights (Hugging Face)",
    "note": "LG AI연구원 최초의 오픈웨이트 비전-언어 파운데이션 모델(VLM). 독자 개발 비전 인코더와 LLM을 결합하여 고난도 도표/문서 이해 및 과학 추론에 탁월.",
    "benchmarks": {
      "MMMU (Multimodal)": 70.8,
      "MMLU": 82.4
    }
  },
  {
    "id": "model-041",
    "name": "Qwen3.6-35B-A3B",
    "date": "2026-04-16",
    "sortDate": "2026-04-16",
    "month": "2026-04",
    "monthName": "April",
    "company": "Alibaba",
    "family": "Qwen3.6",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "35B total / 3B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1355,
      "GPQA Diamond": 81,
      "MMLU-Pro": 77.2,
      "LiveCodeBench": 74
    }
  },
  {
    "id": "model-042",
    "name": "Claude Opus 4.7",
    "date": "2026-04-16",
    "sortDate": "2026-04-16",
    "month": "2026-04",
    "monthName": "April",
    "company": "Anthropic",
    "family": "Claude",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1502,
      "SWE-bench Verified": 74.5,
      "GPQA Diamond": 81.2,
      "MMLU-Pro": 86.4,
      "MMMU (Multimodal)": 75.1
    }
  },
  {
    "id": "model-043",
    "name": "Qwen3.6-Max Preview",
    "date": "2026-04-20",
    "sortDate": "2026-04-20",
    "month": "2026-04",
    "monthName": "April",
    "company": "Alibaba",
    "family": "Qwen3.6",
    "type": "MLLM",
    "category": "MLLM",
    "status": "Preview",
    "parameters": "",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "Alibaba DashScope 플래그십 상용 API 프리뷰 모델 (파라미터 비공개)",
    "benchmarks": {
      "Chatbot Arena ELO": 1425,
      "MMLU-Pro": 86.5,
      "SWE-bench Pro": 58,
      "GPQA Diamond": 89.5
    }
  },
  {
    "id": "model-044",
    "name": "Kimi K2.6",
    "date": "2026-04-20",
    "sortDate": "2026-04-20",
    "month": "2026-04",
    "monthName": "April",
    "company": "Moonshot AI",
    "family": "Kimi",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "~1T MoE",
    "architecture": "Multimodal MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 80.2,
      "SWE-bench Pro": 58.6,
      "AIME 2025": 96.4,
      "MMMU (Multimodal)": 71.2
    }
  },
  {
    "id": "model-045",
    "name": "LongCat-2.0 Preview",
    "date": "2026-04-20",
    "sortDate": "2026-04-20",
    "month": "2026-04",
    "monthName": "April",
    "company": "Meituan",
    "family": "LongCat",
    "type": "LLM",
    "category": "LLM",
    "status": "Preview",
    "parameters": "~1.6T total / ~48B active",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Pro": 54.2,
      "Terminal-Bench 2.1": 64.5,
      "SWE-bench Verified": 68.5
    }
  },
  {
    "id": "model-046",
    "name": "Qwen3.6-27B",
    "date": "2026-04-22",
    "sortDate": "2026-04-22",
    "month": "2026-04",
    "monthName": "April",
    "company": "Alibaba",
    "family": "Qwen3.6",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "27B (Dense)",
    "architecture": "Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1365,
      "GPQA Diamond": 87,
      "SWE-bench Pro": 53.5,
      "MMLU-Pro": 79.5,
      "LiveCodeBench": 78.5
    }
  },
  {
    "id": "model-047",
    "name": "MiMo-V2.5",
    "date": "2026-04-23",
    "sortDate": "2026-04-23",
    "month": "2026-04",
    "monthName": "April",
    "company": "Xiaomi",
    "family": "MiMo",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1375,
      "MMLU": 89.4
    }
  },
  {
    "id": "model-048",
    "name": "MiMo-V2.5-Pro",
    "date": "2026-04-23",
    "sortDate": "2026-04-23",
    "month": "2026-04",
    "monthName": "April",
    "company": "Xiaomi",
    "family": "MiMo",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1405,
      "MMLU": 90.2,
      "SWE-bench Pro": 56.8
    }
  },
  {
    "id": "model-049",
    "name": "GPT-5.5",
    "date": "2026-04-23",
    "sortDate": "2026-04-23",
    "month": "2026-04",
    "monthName": "April",
    "company": "OpenAI",
    "family": "GPT",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1500,
      "SWE-bench Verified": 85,
      "MMLU-Pro": 88,
      "GPQA Diamond": 84,
      "MATH-500": 93.5
    }
  },
  {
    "id": "model-050",
    "name": "GPT-5.5 Pro",
    "date": "2026-04-23",
    "sortDate": "2026-04-23",
    "month": "2026-04",
    "monthName": "April",
    "company": "OpenAI",
    "family": "GPT",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1520,
      "SWE-bench Verified": 88.7,
      "MMLU-Pro": 90.2,
      "GPQA Diamond": 87.5,
      "MATH-500": 95.8
    }
  },
  {
    "id": "model-051",
    "name": "DeepSeek-V4",
    "date": "2026-04-24",
    "sortDate": "2026-04-24",
    "month": "2026-04",
    "monthName": "April",
    "company": "DeepSeek",
    "family": "DeepSeek V4",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~1T total / ~37B active (MoE)",
    "architecture": "MLA + Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1330,
      "MMLU-Pro": 81.5,
      "GPQA Diamond": 85,
      "MATH-500": 90.2,
      "SWE-bench Verified": 72,
      "LiveCodeBench": 88.5
    }
  },
  {
    "id": "model-052",
    "name": "DeepSeek-V4-Flash-Preview",
    "date": "2026-04-24",
    "sortDate": "2026-04-24",
    "month": "2026-04",
    "monthName": "April",
    "company": "DeepSeek",
    "family": "DeepSeek V4",
    "type": "LLM",
    "category": "LLM",
    "status": "Preview",
    "parameters": "~27B / ~3B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1290,
      "MMLU-Pro": 76,
      "GPQA Diamond": 79.5,
      "SWE-bench Verified": 63.5,
      "LiveCodeBench": 81
    }
  },
  {
    "id": "model-053",
    "name": "DeepSeek-V4-Pro-Preview",
    "date": "2026-04-24",
    "sortDate": "2026-04-24",
    "month": "2026-04",
    "monthName": "April",
    "company": "DeepSeek",
    "family": "DeepSeek V4",
    "type": "LLM",
    "category": "LLM",
    "status": "Preview",
    "parameters": "~1T total / ~37B active (MoE)",
    "architecture": "MLA + Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1360,
      "MMLU-Pro": 84,
      "GPQA Diamond": 87.2,
      "SWE-bench Verified": 78.5,
      "LiveCodeBench": 90.2
    }
  },
  {
    "id": "model-054",
    "name": "Hy3 Preview",
    "date": "2026-04-24",
    "sortDate": "2026-04-24",
    "month": "2026-04",
    "monthName": "April",
    "company": "Tencent",
    "family": "Hy / Hunyuan",
    "type": "LLM",
    "category": "LLM",
    "status": "Preview",
    "parameters": "295B total / 21B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "Apache 2.0",
    "context": "256K",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "Open Weights (Hugging Face / GitHub)",
    "note": "텐센트 Hunyuan 3 오픈웨이트 프리뷰. Apache 2.0 라이선스로 295B/21B 활성 MoE 가중치 공개.",
    "benchmarks": {
      "MMLU": 84.2,
      "MATH-500": 78.5,
      "LiveCodeBench": 71
    }
  },
  {
    "id": "model-055",
    "name": "Laguna M.1",
    "date": "2026-04-28",
    "sortDate": "2026-04-28",
    "month": "2026-04",
    "monthName": "April",
    "company": "Poolside",
    "family": "Laguna",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~225B / ~23B active",
    "architecture": "Code MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 64.5,
      "Terminal-Bench 2.1": 58.2
    }
  },
  {
    "id": "model-056",
    "name": "Laguna XS.2",
    "date": "2026-04-28",
    "sortDate": "2026-04-28",
    "month": "2026-04",
    "monthName": "April",
    "company": "Poolside",
    "family": "Laguna",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~33B / ~3B active",
    "architecture": "Code MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 58.2,
      "Terminal-Bench 2.1": 51
    }
  },
  {
    "id": "model-057",
    "name": "Nemotron 3 Nano Omni",
    "date": "2026-04-28",
    "sortDate": "2026-04-28",
    "month": "2026-04",
    "monthName": "April",
    "company": "NVIDIA",
    "family": "Nemotron",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "~8B",
    "architecture": "Edge Omni Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMMU (Multimodal)": 64.2,
      "MMLU": 76.8
    }
  },
  {
    "id": "model-058",
    "name": "Granite 4.1 family",
    "date": "2026-04-29",
    "sortDate": "2026-04-29",
    "month": "2026-04",
    "monthName": "April",
    "company": "IBM",
    "family": "Granite",
    "type": "LLM + MLLM family",
    "category": "MLLM",
    "status": "GA",
    "parameters": "1B, 3B, 8B, 34B (Language) & 3B, 8B (Vision)",
    "architecture": "Mamba2 + Transformer Hybrid",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "speech / embedding / Guardian-only members excluded here",
    "benchmarks": {
      "MMLU-Pro": 71.5,
      "GPQA": 58.2,
      "SWE-bench Verified": 42.1
    }
  },
  {
    "id": "model-var-07",
    "name": "Granite 4.1 Language",
    "date": "2026-04-29",
    "sortDate": "2026-04-29",
    "month": "2026-04",
    "monthName": "April",
    "company": "IBM",
    "family": "Granite",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "1B, 3B, 8B, 34B",
    "architecture": "Mamba2 + Transformer Hybrid",
    "open_weights": true,
    "note": "IBM 차세대 엔터프라이즈 오픈 파운데이션 모델",
    "benchmarks": {
      "MMLU-Pro": 71.5,
      "GPQA": 58.2,
      "SWE-bench Verified": 42.1
    }
  },
  {
    "id": "model-var-08",
    "name": "Granite 4.1 Vision",
    "date": "2026-04-29",
    "sortDate": "2026-04-29",
    "month": "2026-04",
    "monthName": "April",
    "company": "IBM",
    "family": "Granite",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "3B, 8B",
    "architecture": "Vision-Language Multimodal Transformer",
    "open_weights": true,
    "note": "IBM Granite 시각-언어 멀티모달 오픈 모델",
    "benchmarks": {
      "MMMU (Multimodal)": 58.4,
      "MMLU": 68.2
    }
  },
  {
    "id": "model-059",
    "name": "ERNIE 5.1",
    "date": "2026-05-09",
    "sortDate": "2026-05-09",
    "month": "2026-05",
    "monthName": "May",
    "company": "Baidu",
    "family": "ERNIE",
    "type": "LLM / agentic foundation model",
    "category": "LLM",
    "status": "GA",
    "parameters": "~1.2T",
    "architecture": "Agentic Foundation Model",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "Reduced model size relative to ERNIE 5.0 Improved reasoning and agent capabilities",
    "benchmarks": {
      "Chatbot Arena ELO": 1485,
      "MMLU": 88.2,
      "MMMU (Multimodal)": 72.5
    }
  },
  {
    "id": "model-127",
    "name": "A.X Telco LLM",
    "date": "2026-05-14",
    "sortDate": "2026-05-14",
    "month": "2026-05",
    "monthName": "May",
    "company": "SK Telecom",
    "family": "A.X",
    "type": "LLM",
    "category": "Reasoning",
    "status": "GA",
    "parameters": "70B",
    "architecture": "Domain-Adapted Autoregressive Transformer",
    "modalities": [
      "language",
      "code"
    ],
    "focus": [
      "Global Telco AI Alliance",
      "telecom customer operations",
      "network diagnosis",
      "multilingual agent"
    ],
    "open_weights": false,
    "license": "Proprietary / Global Telco AI Alliance",
    "context": "128K",
    "languages": "Korean, English, Japanese, Arabic, German",
    "variants": [
      "70B Telco"
    ],
    "reasoning_effort": [],
    "availability": "GTAA Alliance Cloud / SKT Enterprise",
    "note": "글로벌 텔코 AI 얼라이언스(GTAA)와 협력하여 통신 도메인 지식, 고객 상담 및 네트워크 인프라 진단에 특화 개발된 통신 전용 70B 모델.",
    "benchmarks": {
      "TelBench": 87.2,
      "TelAgentBench": 81.5,
      "LiveCodeBench": 68.4
    }
  },
  {
    "id": "model-060",
    "name": "Gemini 3.5 Flash",
    "date": "2026-05-19",
    "sortDate": "2026-05-19",
    "month": "2026-05",
    "monthName": "May",
    "company": "Google DeepMind",
    "family": "Gemini",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [
      "agents",
      "coding",
      "multimodal reasoning"
    ],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1475,
      "MMMU (Multimodal)": 76.5,
      "SWE-bench Verified": 78.2
    }
  },
  {
    "id": "model-061",
    "name": "Qwen3.7-Max",
    "date": "2026-05-20",
    "sortDate": "2026-05-20",
    "month": "2026-05",
    "monthName": "May",
    "company": "Alibaba",
    "family": "Qwen3.7",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "Alibaba DashScope 플래그십 상용 API 모델 (파라미터 비공개)",
    "benchmarks": {
      "Chatbot Arena ELO": 1435,
      "MMLU-Pro": 87.5,
      "SWE-bench Pro": 61.5,
      "GPQA Diamond": 90.8
    }
  },
  {
    "id": "model-062",
    "name": "Command A+",
    "date": "2026-05-20",
    "sortDate": "2026-05-20",
    "month": "2026-05",
    "monthName": "May",
    "company": "Cohere",
    "family": "Command",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [
      "sovereign / agentic enterprise AI"
    ],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1390,
      "MMLU": 85.2,
      "AA Intelligence Index": 64
    }
  },
  {
    "id": "model-063",
    "name": "Mistral Medium 3.5",
    "date": "2026-05-22",
    "sortDate": "2026-05-22",
    "month": "2026-05",
    "monthName": "May",
    "company": "Mistral AI",
    "family": "Mistral Medium",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Dense Transformer",
    "modalities": [],
    "focus": [
      "agents",
      "coding",
      "knowledge work"
    ],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "Mistral AI의 상용 API 전용 모델 (파라미터 비공개)",
    "benchmarks": {
      "Chatbot Arena ELO": 1385,
      "SWE-bench Verified": 77.6,
      "MMLU-Pro": 80.5
    }
  },
  {
    "id": "model-064",
    "name": "Claude Opus 4.8",
    "date": "2026-05-28",
    "sortDate": "2026-05-28",
    "month": "2026-05",
    "monthName": "May",
    "company": "Anthropic",
    "family": "Claude",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1512,
      "SWE-bench Verified": 88.6,
      "GPQA Diamond": 84.5,
      "MMLU-Pro": 88.2,
      "MMMU (Multimodal)": 77.4
    }
  },
  {
    "id": "model-065",
    "name": "MiniMax M3",
    "date": "2026-06-01",
    "sortDate": "2026-06-01",
    "month": "2026-06",
    "monthName": "June",
    "company": "MiniMax",
    "family": "MiniMax M",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Multimodal MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1395,
      "MMLU-Pro": 84.2,
      "SWE-bench Pro": 59,
      "MMMU (Multimodal)": 70.4
    }
  },
  {
    "id": "model-066",
    "name": "Qwen3.7-Plus",
    "date": "2026-06-02",
    "sortDate": "2026-06-02",
    "month": "2026-06",
    "monthName": "June",
    "company": "Alibaba",
    "family": "Qwen3.7",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "Alibaba DashScope 상용 API 모델 (파라미터 비공개)",
    "benchmarks": {
      "Chatbot Arena ELO": 1420,
      "MMLU-Pro": 86,
      "SWE-bench Verified": 79,
      "LiveCodeBench": 84.5
    }
  },
  {
    "id": "model-067",
    "name": "Nemotron 3 Ultra",
    "date": "2026-06-04",
    "sortDate": "2026-06-04",
    "month": "2026-06",
    "monthName": "June",
    "company": "NVIDIA",
    "family": "Nemotron 3",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~500B",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU": 89.1,
      "MMLU-Pro": 79,
      "MATH-500": 84.5,
      "LiveCodeBench": 78.5
    }
  },
  {
    "id": "model-068",
    "name": "Claude Fable 5",
    "date": "2026-06-09",
    "sortDate": "2026-06-09",
    "month": "2026-06",
    "monthName": "June",
    "company": "Anthropic",
    "family": "Claude",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1528,
      "SWE-bench Verified": 95,
      "SWE-bench Pro": 80.3,
      "GPQA Diamond": 88.9,
      "MMLU-Pro": 90.5
    }
  },
  {
    "id": "model-069",
    "name": "Claude Mythos 5",
    "date": "2026-06-09",
    "sortDate": "2026-06-09",
    "month": "2026-06",
    "monthName": "June",
    "company": "Anthropic",
    "family": "Claude",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "restricted / vetted users",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1528,
      "SWE-bench Verified": 95,
      "SWE-bench Pro": 80.3,
      "GPQA Diamond": 88.9,
      "MMLU-Pro": 90.5
    }
  },
  {
    "id": "model-070",
    "name": "North Mini Code",
    "date": "2026-06-09",
    "sortDate": "2026-06-09",
    "month": "2026-06",
    "monthName": "June",
    "company": "Cohere",
    "family": "North",
    "type": "LLM / coding",
    "category": "LLM",
    "status": "GA",
    "parameters": "30B total / 3B active",
    "architecture": "Code MoE Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "Apache 2.0",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 67.6,
      "LiveCodeBench": 74.5
    }
  },
  {
    "id": "model-071",
    "name": "Kimi K2.7 Code",
    "date": "2026-06-12",
    "sortDate": "2026-06-12",
    "month": "2026-06",
    "monthName": "June",
    "company": "Moonshot AI",
    "family": "Kimi",
    "type": "MLLM / coding",
    "category": "MLLM",
    "status": "GA",
    "parameters": "~1T MoE",
    "architecture": "Code Multimodal MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 60.4,
      "LiveCodeBench": 85.2,
      "HumanEval": 94.1,
      "AIME 2025": 97.4
    }
  },
  {
    "id": "model-072",
    "name": "Ling-2.6-1T",
    "date": "2026-06-13~21",
    "sortDate": "2026-06-13",
    "month": "2026-06",
    "monthName": "June",
    "company": "Ant Group / InclusionAI",
    "family": "Ling",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~1T",
    "architecture": "MLA + Linear Attention hybrid",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 78.5,
      "AIME 2026": 94.2,
      "IFEval": 84.6,
      "AA Intelligence Index": 34
    }
  },
  {
    "id": "model-073",
    "name": "Ring-2.6-1T",
    "date": "2026-06-13~21",
    "sortDate": "2026-06-13",
    "month": "2026-06",
    "monthName": "June",
    "company": "Ant Group / InclusionAI",
    "family": "Ring",
    "type": "reasoning LLM",
    "category": "Reasoning",
    "status": "GA",
    "parameters": "~1T",
    "architecture": "Reasoning LLM (MLA + Linear Attention)",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [
      "high",
      "xhigh"
    ],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 81.2,
      "AIME 2026": 96.8
    }
  },
  {
    "id": "model-074",
    "name": "HyperCLOVA X SEED 4B",
    "date": "2026-06-15",
    "sortDate": "2026-06-15",
    "month": "2026-06",
    "monthName": "June",
    "company": "NAVER Cloud",
    "family": "HyperCLOVA X SEED",
    "type": "MLLM / lightweight omni",
    "category": "Omni",
    "status": "GA",
    "parameters": "4B",
    "architecture": "Lightweight Omni (Edge/Defense)",
    "modalities": [
      "language",
      "vision",
      "audio"
    ],
    "focus": [
      "edge / on-device / defense environments"
    ],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMMU (Multimodal)": 54.2,
      "MMLU-Pro": 52.8
    }
  },
  {
    "id": "model-075",
    "name": "GLM-5.2",
    "date": "2026-06-16",
    "sortDate": "2026-06-16",
    "month": "2026-06",
    "monthName": "June",
    "company": "Z.ai",
    "family": "GLM",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "744B total / ~40B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1410,
      "MMLU-Pro": 83.5,
      "LiveCodeBench": 83.8,
      "SWE-bench Verified": 74.2
    }
  },
  {
    "id": "model-076",
    "name": "LongCat-2.0",
    "date": "2026-06-30",
    "sortDate": "2026-06-30",
    "month": "2026-06",
    "monthName": "June",
    "company": "Meituan",
    "family": "LongCat",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~1.6T total / ~48B average active",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Pro": 59.5,
      "SWE-bench Verified": 75.8,
      "Terminal-Bench 2.1": 70.8
    }
  },
  {
    "id": "model-077",
    "name": "Claude Sonnet 5",
    "date": "2026-06-30",
    "sortDate": "2026-06-30",
    "month": "2026-06",
    "monthName": "June",
    "company": "Anthropic",
    "family": "Claude",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1505,
      "SWE-bench Verified": 89.2,
      "GPQA Diamond": 85,
      "MMLU-Pro": 87.8,
      "MMMU (Multimodal)": 78.5
    }
  },
  {
    "id": "model-078",
    "name": "Laguna XS 2.1",
    "date": "2026-07-02",
    "sortDate": "2026-07-02",
    "month": "2026-07",
    "monthName": "July",
    "company": "Poolside",
    "family": "Laguna",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~33B / ~3B active",
    "architecture": "Code MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 70.9,
      "SWE-bench Pro": 47.6,
      "Terminal-Bench 2.1": 61.5
    }
  },
  {
    "id": "model-079",
    "name": "Hy3",
    "date": "2026-07-06",
    "sortDate": "2026-07-06",
    "month": "2026-07",
    "monthName": "July",
    "company": "Tencent",
    "family": "Hy / Hunyuan",
    "type": "LLM",
    "category": "LLM",
    "status": "Stable",
    "parameters": "295B total / 21B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "Apache 2.0",
    "context": "256K",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "Open Weights (Hugging Face / GitHub)",
    "note": "텐센트 Hunyuan 3 정식 오픈웨이트 릴리스. Apache 2.0 라이선스로 295B MoE(21B 활성), 256K 컨텍스트 가중치 공개.",
    "benchmarks": {
      "MMLU": 86,
      "MATH-500": 82.4,
      "LiveCodeBench": 75.8
    }
  },
  {
    "id": "model-080",
    "name": "Muse Spark 1.1",
    "date": "2026-07-09",
    "sortDate": "2026-07-09",
    "month": "2026-07",
    "monthName": "July",
    "company": "Meta",
    "family": "Muse Spark",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1480,
      "AA Intelligence Index": 54
    }
  },
  {
    "id": "model-081",
    "name": "GPT-5.6 Sol",
    "date": "2026-07-09",
    "sortDate": "2026-07-09",
    "month": "2026-07",
    "monthName": "July",
    "company": "OpenAI",
    "family": "GPT-5.6",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1545,
      "SWE-bench Verified": 95.5,
      "Terminal-Bench 2.1": 91.9,
      "MMLU-Pro": 92.8,
      "GPQA Diamond": 92,
      "MATH-500": 97.5
    }
  },
  {
    "id": "model-082",
    "name": "GPT-5.6 Terra",
    "date": "2026-07-09",
    "sortDate": "2026-07-09",
    "month": "2026-07",
    "monthName": "July",
    "company": "OpenAI",
    "family": "GPT-5.6",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1495,
      "SWE-bench Verified": 87.5,
      "Terminal-Bench 2.1": 82.4,
      "MMLU-Pro": 87,
      "GPQA Diamond": 83.5,
      "MATH-500": 91.5
    }
  },
  {
    "id": "model-083",
    "name": "GPT-5.6 Luna",
    "date": "2026-07-09",
    "sortDate": "2026-07-09",
    "month": "2026-07",
    "monthName": "July",
    "company": "OpenAI",
    "family": "GPT-5.6",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1425,
      "SWE-bench Verified": 74,
      "Terminal-Bench 2.1": 68.1,
      "MMLU-Pro": 79.5,
      "GPQA Diamond": 71,
      "MATH-500": 84
    }
  },
  {
    "id": "model-084",
    "name": "Motif 3 Beta",
    "date": "2026-07-14",
    "sortDate": "2026-07-14",
    "month": "2026-07",
    "monthName": "July",
    "company": "Motif Technologies",
    "family": "Motif",
    "type": "LLM",
    "category": "LLM",
    "status": "Beta",
    "parameters": "~314B total / ~13.2B active",
    "architecture": "MoE + GDLA + MTP",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 71.5,
      "Terminal-Bench 2.1": 68.4
    }
  },
  {
    "id": "model-085",
    "name": "Inkling",
    "date": "2026-07-15",
    "sortDate": "2026-07-15",
    "month": "2026-07",
    "monthName": "July",
    "company": "Thinking Machines Lab",
    "family": "Inkling",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "~975B total / ~41B active",
    "architecture": "Native Multimodal MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMMU-Pro": 68.5,
      "LiveCodeBench": 82
    }
  },
  {
    "id": "model-086",
    "name": "Grok 4.5",
    "date": "2026-07-16",
    "sortDate": "2026-07-16",
    "month": "2026-07",
    "monthName": "July",
    "company": "xAI / SpaceXAI",
    "family": "Grok",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [
      "coding",
      "agents",
      "knowledge work"
    ],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1485,
      "SWE-bench Pro": 63.2,
      "Terminal-Bench 2.1": 65.8,
      "AA Intelligence Index": 56
    }
  },
  {
    "id": "model-087",
    "name": "Kimi K3",
    "date": "2026-07-17",
    "sortDate": "2026-07-17",
    "month": "2026-07",
    "monthName": "July",
    "company": "Moonshot AI",
    "family": "Kimi",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "~2.8T",
    "architecture": "Long-Context (1M) MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "~1M",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 76.8,
      "AIME 2025": 96.1,
      "MMLU-Pro": 87.2,
      "LiveCodeBench": 88,
      "MMMU (Multimodal)": 74.5
    }
  },
  {
    "id": "model-088",
    "name": "Qwen3.8-Max Preview",
    "date": "2026-07-19",
    "sortDate": "2026-07-19",
    "month": "2026-07",
    "monthName": "July",
    "company": "Alibaba",
    "family": "Qwen3.8",
    "type": "MLLM",
    "category": "MLLM",
    "status": "Preview",
    "parameters": "",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "Alibaba DashScope 플래그십 상용 API 프리뷰 모델 (파라미터 비공개)",
    "benchmarks": {
      "Chatbot Arena ELO": 1440,
      "MMLU-Pro": 88,
      "SWE-bench Pro": 64,
      "GPQA Diamond": 91.5
    }
  },
  {
    "id": "model-089",
    "name": "Gemini 3.6 Flash",
    "date": "2026-07-21",
    "sortDate": "2026-07-21",
    "month": "2026-07",
    "monthName": "July",
    "company": "Google DeepMind",
    "family": "Gemini",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1495,
      "MMMU (Multimodal)": 78.8,
      "SWE-bench Verified": 82.5
    }
  },
  {
    "id": "model-090",
    "name": "Gemini 3.5 Flash-Lite",
    "date": "2026-07-21",
    "sortDate": "2026-07-21",
    "month": "2026-07",
    "monthName": "July",
    "company": "Google DeepMind",
    "family": "Gemini",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1420,
      "MMLU-Pro": 79.2,
      "LiveCodeBench": 74
    }
  },
  {
    "id": "model-091",
    "name": "Gemini 3.5 Flash Cyber",
    "date": "2026-07-21",
    "sortDate": "2026-07-21",
    "month": "2026-07",
    "monthName": "July",
    "company": "Google DeepMind",
    "family": "Gemini",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [
      "cybersecurity"
    ],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "CyberGym": 84.5,
      "SWE-bench Verified": 79.5
    }
  },
  {
    "id": "model-092",
    "name": "Laguna S 2.1",
    "date": "2026-07-21",
    "sortDate": "2026-07-21",
    "month": "2026-07",
    "monthName": "July",
    "company": "Poolside",
    "family": "Laguna",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~70B",
    "architecture": "Code Dense/MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 78.5,
      "SWE-bench Pro": 59.4,
      "Terminal-Bench 2.1": 70.2
    }
  },
  {
    "id": "model-093",
    "name": "Solar Open 2",
    "date": "2026-07-22",
    "sortDate": "2026-07-22",
    "month": "2026-07",
    "monthName": "July",
    "company": "Upstage",
    "family": "Solar Open",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~250B total / ~15B active",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "~1M",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU-Pro": 86.2,
      "LiveCodeBench": 92.4
    }
  },
  {
    "id": "model-094",
    "name": "Claude Opus 5",
    "date": "2026-07-24",
    "sortDate": "2026-07-24",
    "month": "2026-07",
    "monthName": "July",
    "company": "Anthropic",
    "family": "Claude",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1535,
      "SWE-bench Verified": 96,
      "SWE-bench Pro": 79.2,
      "GPQA Diamond": 91.2,
      "MMLU-Pro": 92.1,
      "MMMU (Multimodal)": 82
    }
  },
  {
    "id": "model-128",
    "name": "A.X K2",
    "date": "2026-07-28",
    "sortDate": "2026-07-28",
    "month": "2026-07",
    "monthName": "July",
    "company": "SK Telecom",
    "family": "A.X",
    "type": "MLLM",
    "category": "Omni",
    "status": "GA",
    "parameters": "688B (Multi-modal 688B parameters)",
    "architecture": "Multimodal Agentic Architecture (Omni / Native End-to-End)",
    "modalities": [
      "language",
      "vision",
      "speech",
      "agent actions"
    ],
    "focus": [
      "Real-time multimodal conversation",
      "AI for All national service",
      "Telco AI Agent"
    ],
    "open_weights": false,
    "license": "Proprietary",
    "context": "256K",
    "languages": "Korean, English",
    "variants": [
      "K2 688B Omni"
    ],
    "reasoning_effort": [],
    "availability": "SKT A. Service / Government AI for All",
    "note": "688B 파라미터 규모의 차세대 멀티모달 옴니 파운데이션 모델. 음성·영상·문서를 통합 인식하며 SKT '전국민 AI(AI for All)' 서비스의 핵심 엔진.",
    "benchmarks": {
      "AIME 2026": 97.1,
      "KMMLU-Pro": 80.5,
      "LiveCodeBench": 82.4,
      "MMMU (Multimodal)": 73.5
    }
  },
  {
    "id": "model-095",
    "name": "Inkling-Small",
    "date": "2026-07-30",
    "sortDate": "2026-07-30",
    "month": "2026-07",
    "monthName": "July",
    "company": "Thinking Machines Lab",
    "family": "Inkling",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "~276B total / ~12B active",
    "architecture": "Native Multimodal MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMMU-Pro": 62,
      "LiveCodeBench": 76.5
    }
  },
  {
    "id": "model-096",
    "name": "DeepSeek-V4-Flash",
    "date": "2026-07-31",
    "sortDate": "2026-07-31",
    "month": "2026-07",
    "monthName": "July",
    "company": "DeepSeek",
    "family": "DeepSeek V4",
    "type": "LLM",
    "category": "LLM",
    "status": "Public beta / official Flash release",
    "parameters": "~27B / ~3B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1350,
      "LiveCodeBench": 91.6,
      "SWE-bench Verified": 79,
      "Terminal-Bench 2.1": 82.7,
      "GPQA Diamond": 88.1,
      "MMLU-Pro": 84.2,
      "MATH-500": 93.8
    }
  },
  {
    "id": "model-097",
    "name": "Qwen3.8-Max",
    "date": "2026-08-03",
    "sortDate": "2026-08-03",
    "month": "2026-08",
    "monthName": "August",
    "company": "Alibaba",
    "family": "Qwen3.8",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": false,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "Alibaba DashScope 플래그십 상용 API 모델 (파라미터 비공개)",
    "benchmarks": {
      "Chatbot Arena ELO": 1450,
      "SWE-bench Pro": 67.7,
      "GPQA Diamond": 92.6,
      "MMLU-Pro": 88.5,
      "MMMU (Multimodal)": 81.5
    }
  },
  {
    "id": "model-098",
    "name": "Muse Spark 1.2",
    "date": "2026-08-05",
    "sortDate": "2026-08-05",
    "month": "2026-08",
    "monthName": "August",
    "company": "Meta",
    "family": "Muse Spark",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1505,
      "AA Intelligence Index": 58
    }
  },
  {
    "id": "model-099",
    "name": "Motif 3",
    "date": "2026-08-10~12",
    "sortDate": "2026-08-10",
    "month": "2026-08",
    "monthName": "August",
    "company": "Motif Technologies",
    "family": "Motif",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~314B total / ~13.2B active",
    "architecture": "MoE, GDLA, MTP",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "Technical/public-release dates differ slightly by source.",
    "benchmarks": {
      "SWE-bench Verified": 76.2,
      "Terminal-Bench 2.1": 74.9,
      "AA Intelligence Index": 47
    }
  },
  {
    "id": "model-100",
    "name": "Qwen3.8-2.4T-A95B",
    "date": "2026-08-12",
    "sortDate": "2026-08-12",
    "month": "2026-08",
    "monthName": "August",
    "company": "Alibaba",
    "family": "Qwen3.8",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "2.4T total / 95B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1445,
      "SWE-bench Pro": 66.5,
      "GPQA Diamond": 92,
      "MMLU-Pro": 88.2,
      "LiveCodeBench": 89.5
    }
  },
  {
    "id": "model-101",
    "name": "Grok 4.6",
    "date": "2026-08-12",
    "sortDate": "2026-08-12",
    "month": "2026-08",
    "monthName": "August",
    "company": "xAI / SpaceXAI",
    "family": "Grok",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [
      "text",
      "image"
    ],
    "focus": [
      "long-running agents",
      "coding",
      "visual work",
      "knowledge work"
    ],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1515,
      "SWE-bench Pro": 69.4,
      "Terminal-Bench 2.1": 71.2,
      "AA Intelligence Index": 61
    }
  },
  {
    "id": "model-129",
    "name": "K-EXAONE 2.0",
    "date": "2026-08-12",
    "sortDate": "2026-08-12",
    "month": "2026-08",
    "monthName": "August",
    "company": "LG AI Research",
    "family": "EXAONE",
    "type": "LLM",
    "category": "Reasoning",
    "status": "GA",
    "parameters": "~260B total / ~28B active (Sparse MoE)",
    "architecture": "Sparse Mixture-of-Experts (MoE)",
    "modalities": [
      "language",
      "code"
    ],
    "focus": [
      "Sovereign AI",
      "Korean deep reasoning",
      "materials science / industrial AI"
    ],
    "open_weights": true,
    "license": "EXAONE Open License",
    "context": "256K",
    "languages": "Korean, English",
    "variants": [
      "260B MoE"
    ],
    "reasoning_effort": [],
    "availability": "Open Weights (Research & Sovereign AI)",
    "note": "한국 정부 독자 소버린 AI 파운데이션 모델 프로젝트의 일환으로 공개된 대규모 MoE 추론 모델. 물질 과학 및 산업 도메인 특화 지식 탑재.",
    "benchmarks": {
      "IFEval": 86.4,
      "MMLU-Pro": 78.5,
      "SWE-bench Verified": 61.2
    }
  },
  {
    "id": "model-102",
    "name": "DeepSeek-V4-Pro",
    "date": "2026-08-13",
    "sortDate": "2026-08-13",
    "month": "2026-08",
    "monthName": "August",
    "company": "DeepSeek",
    "family": "DeepSeek V4",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~1T total / ~37B active (MoE)",
    "architecture": "MLA + Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1415,
      "LiveCodeBench": 93.5,
      "SWE-bench Verified": 95.2,
      "Terminal-Bench 2.1": 87.9,
      "GPQA Diamond": 90.1,
      "MMLU-Pro": 87.5,
      "MATH-500": 96.5
    }
  },
  {
    "id": "model-103",
    "name": "Gemini 3.7 Flash",
    "date": "2026-08-13",
    "sortDate": "2026-08-13",
    "month": "2026-08",
    "monthName": "August",
    "company": "Google DeepMind",
    "family": "Gemini",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [
      "coding",
      "agents",
      "knowledge work"
    ],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1515,
      "SWE-bench Verified": 88,
      "Terminal-Bench 2.1": 86.5,
      "MMMU (Multimodal)": 82
    }
  },
  {
    "id": "model-104",
    "name": "Qwen3.8-27B",
    "date": "2026-08-14",
    "sortDate": "2026-08-14",
    "month": "2026-08",
    "monthName": "August",
    "company": "Alibaba",
    "family": "Qwen3.8",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "27B (Dense)",
    "architecture": "Dense Transformer",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1380,
      "GPQA Diamond": 89.2,
      "SWE-bench Pro": 56.5,
      "MMLU-Pro": 82,
      "LiveCodeBench": 82.5
    }
  },
  {
    "id": "model-105",
    "name": "GLM-5.3",
    "date": "2026-08-14",
    "sortDate": "2026-08-14",
    "month": "2026-08",
    "monthName": "August",
    "company": "Z.ai",
    "family": "GLM",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "744B total / ~40B active (MoE)",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1430,
      "MMLU-Pro": 85.6,
      "LiveCodeBench": 87.2,
      "SWE-bench Verified": 78.9
    }
  },
  {
    "id": "model-106",
    "name": "DeepSeek-V4-Flash Vision Exp",
    "date": "2026-08-21",
    "sortDate": "2026-08-21",
    "month": "2026-08",
    "monthName": "August",
    "company": "DeepSeek",
    "family": "DeepSeek V4",
    "type": "MLLM",
    "category": "MLLM",
    "status": "Experimental",
    "parameters": "~27B (MLLM MoE)",
    "architecture": "Vision-Language MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMMU (Multimodal)": 76.4,
      "LiveCodeBench": 88.5,
      "GPQA Diamond": 84.5
    }
  },
  {
    "id": "model-107",
    "name": "Ling-3.0-tiny",
    "date": "2026-08-21~22",
    "sortDate": "2026-08-21",
    "month": "2026-08",
    "monthName": "August",
    "company": "Ant Group / InclusionAI",
    "family": "Ling 3.0",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~8B",
    "architecture": "Dense Linear Attention",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "MMLU": 79.5,
      "LiveCodeBench": 68.2,
      "IFEval": 76.5
    }
  },
  {
    "id": "model-108",
    "name": "Ling-3.0-flash",
    "date": "2026-08-21~22",
    "sortDate": "2026-08-21",
    "month": "2026-08",
    "monthName": "August",
    "company": "Ant Group / InclusionAI",
    "family": "Ling 3.0",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "124B total / 5.1B active",
    "architecture": "KDA + MLA hybrid linear attention, sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": [
      "256K native",
      "expandable toward 1M"
    ],
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Verified": 79.8,
      "AIME 2026": 95.4,
      "LiveCodeBench": 84.2,
      "IFEval": 85.2
    }
  },
  {
    "id": "model-109",
    "name": "Granite 4.2",
    "date": "2026-08-25",
    "sortDate": "2026-08-25",
    "month": "2026-08",
    "monthName": "August",
    "company": "IBM",
    "family": "Granite",
    "type": "LLM family",
    "category": "LLM",
    "status": "GA",
    "parameters": "3B, 8B, 34B",
    "architecture": "Reasoning & Agentic Transformer",
    "modalities": [],
    "focus": [
      "native reasoning",
      "coding",
      "tool use",
      "agents"
    ],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "speech-only members omitted",
    "benchmarks": {
      "SWE-bench Verified": 57,
      "MMLU-Pro": 77.6,
      "GPQA": 66.4,
      "AIME 2025": 89.2,
      "Terminal-Bench 2.1": 29.2
    }
  },
  {
    "id": "model-110",
    "name": "Qwen3.8-Flash-Next",
    "date": "2026-08-26",
    "sortDate": "2026-08-26",
    "month": "2026-08",
    "monthName": "August",
    "company": "Alibaba",
    "family": "Qwen3.8",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "125B A6B + 51B N-gram",
    "architecture": "next-generation hybrid / efficient architecture",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "SWE-bench Pro": 62.5,
      "MMLU-Pro": 73.2,
      "GPQA Diamond": 91.7,
      "LiveCodeBench": 91.9
    }
  },
  {
    "id": "model-111",
    "name": "GLM-5.3-Flash",
    "date": "2026-08-26",
    "sortDate": "2026-08-26",
    "month": "2026-08",
    "monthName": "August",
    "company": "Z.ai",
    "family": "GLM",
    "type": "LLM",
    "category": "LLM",
    "status": "GA",
    "parameters": "~30B / ~3B active",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1355,
      "MMLU": 86.4,
      "LiveCodeBench": 79.5,
      "SWE-bench Verified": 64
    }
  },
  {
    "id": "model-112",
    "name": "Hy4 Preview",
    "date": "2026-08-28",
    "sortDate": "2026-08-28",
    "month": "2026-08",
    "monthName": "August",
    "company": "Tencent",
    "family": "Hy / Hunyuan",
    "type": "LLM",
    "category": "LLM",
    "status": "Preview",
    "parameters": "770B total / 49B active (MoE) + 10B MTP",
    "architecture": "Sparse MoE",
    "modalities": [],
    "focus": [],
    "open_weights": true,
    "license": "Apache 2.0",
    "context": ">1M",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "Open Weights (Hugging Face / GitHub)",
    "note": "텐센트(Tencent)의 770B 초대형 오픈웨이트 MoE 모델. Apache 2.0 라이선스로 Hugging Face 및 GitHub에 가중치 전면 공개. 49B 활성 파라미터, 10B MTP(Multi-Token Prediction) 레이어, 1M+ 컨텍스트 지원.",
    "benchmarks": {
      "MMLU": 88.4,
      "SWE-bench Verified": 72.8,
      "LiveCodeBench": 83.5,
      "GPQA Diamond": 84.2
    }
  },
  {
    "id": "model-113",
    "name": "Claude Fable 5.1",
    "date": "2026-09-01",
    "sortDate": "2026-09-01",
    "month": "2026-09",
    "monthName": "September",
    "company": "Anthropic",
    "family": "Claude",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1542,
      "SWE-bench Verified": 96.5,
      "SWE-bench Pro": 82.1,
      "GPQA Diamond": 92.5,
      "MMLU-Pro": 93
    }
  },
  {
    "id": "model-114",
    "name": "Claude Mythos 5.1",
    "date": "2026-09-01",
    "sortDate": "2026-09-01",
    "month": "2026-09",
    "monthName": "September",
    "company": "Anthropic",
    "family": "Claude",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "restricted",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1542,
      "SWE-bench Verified": 96.5,
      "SWE-bench Pro": 82.1,
      "GPQA Diamond": 92.5,
      "MMLU-Pro": 93
    }
  },
  {
    "id": "model-115",
    "name": "Muse Spark 1.3",
    "date": "2026-09-02",
    "sortDate": "2026-09-02",
    "month": "2026-09",
    "monthName": "September",
    "company": "Meta",
    "family": "Muse Spark",
    "type": "MLLM",
    "category": "MLLM",
    "status": "GA",
    "parameters": "",
    "architecture": "",
    "modalities": [],
    "focus": [],
    "open_weights": null,
    "license": "",
    "context": "",
    "languages": "",
    "variants": [],
    "reasoning_effort": [],
    "availability": "",
    "note": "",
    "benchmarks": {
      "Chatbot Arena ELO": 1530,
      "AA Intelligence Index": 63
    }
  }
];

const COMPANY_META = {
  "Alibaba": {
    "country": "CN",
    "flag": "🇨🇳",
    "color": "from-orange-500 to-amber-500",
    "badge": "bg-orange-500/10 text-orange-400 border-orange-500/30"
  },
  "Anthropic": {
    "country": "US",
    "flag": "🇺🇸",
    "color": "from-amber-600 to-yellow-500",
    "badge": "bg-amber-500/10 text-amber-400 border-amber-500/30"
  },
  "Ant Group / InclusionAI": {
    "country": "CN",
    "flag": "🇨🇳",
    "color": "from-blue-600 to-indigo-500",
    "badge": "bg-blue-500/10 text-blue-400 border-blue-500/30"
  },
  "Arcee AI": {
    "country": "US",
    "flag": "🇺🇸",
    "color": "from-teal-500 to-emerald-500",
    "badge": "bg-teal-500/10 text-teal-400 border-teal-500/30"
  },
  "Baidu": {
    "country": "CN",
    "flag": "🇨🇳",
    "color": "from-blue-500 to-sky-400",
    "badge": "bg-sky-500/10 text-sky-400 border-sky-500/30"
  },
  "ByteDance": {
    "country": "CN",
    "flag": "🇨🇳",
    "color": "from-cyan-500 to-blue-500",
    "badge": "bg-cyan-500/10 text-cyan-400 border-cyan-500/30"
  },
  "Cohere": {
    "country": "CA",
    "flag": "🇨🇦",
    "color": "from-emerald-500 to-teal-400",
    "badge": "bg-emerald-500/10 text-emerald-400 border-emerald-500/30"
  },
  "Cohere Labs": {
    "country": "CA",
    "flag": "🇨🇦",
    "color": "from-emerald-500 to-teal-400",
    "badge": "bg-emerald-500/10 text-emerald-400 border-emerald-500/30"
  },
  "DeepSeek": {
    "country": "CN",
    "flag": "🇨🇳",
    "color": "from-cyan-400 to-blue-600",
    "badge": "bg-cyan-500/10 text-cyan-300 border-cyan-500/30"
  },
  "Google DeepMind": {
    "country": "US",
    "flag": "🇺🇸",
    "color": "from-blue-400 via-indigo-400 to-purple-500",
    "badge": "bg-indigo-500/10 text-indigo-300 border-indigo-500/30"
  },
  "IBM": {
    "country": "US",
    "flag": "🇺🇸",
    "color": "from-blue-700 to-indigo-600",
    "badge": "bg-blue-700/10 text-blue-300 border-blue-700/30"
  },
  "Meituan": {
    "country": "CN",
    "flag": "🇨🇳",
    "color": "from-yellow-400 to-amber-500",
    "badge": "bg-yellow-500/10 text-yellow-400 border-yellow-500/30"
  },
  "Meta": {
    "country": "US",
    "flag": "🇺🇸",
    "color": "from-blue-600 to-sky-400",
    "badge": "bg-blue-600/10 text-blue-400 border-blue-500/30"
  },
  "MiniMax": {
    "country": "CN",
    "flag": "🇨🇳",
    "color": "from-violet-500 to-purple-600",
    "badge": "bg-violet-500/10 text-violet-300 border-violet-500/30"
  },
  "Mistral AI": {
    "country": "FR",
    "flag": "🇫🇷",
    "color": "from-orange-600 to-amber-500",
    "badge": "bg-orange-600/10 text-orange-300 border-orange-600/30"
  },
  "Moonshot AI": {
    "country": "CN",
    "flag": "🇨🇳",
    "color": "from-purple-500 to-pink-500",
    "badge": "bg-purple-500/10 text-purple-300 border-purple-500/30"
  },
  "Motif Technologies": {
    "country": "US",
    "flag": "🇺🇸",
    "color": "from-rose-500 to-pink-500",
    "badge": "bg-rose-500/10 text-rose-300 border-rose-500/30"
  },
  "NAVER Cloud": {
    "country": "KR",
    "flag": "🇰🇷",
    "color": "from-green-500 to-emerald-500",
    "badge": "bg-green-500/10 text-green-300 border-green-500/30"
  },
  "NVIDIA": {
    "country": "US",
    "flag": "🇺🇸",
    "color": "from-green-600 to-lime-500",
    "badge": "bg-lime-500/10 text-lime-400 border-lime-500/30"
  },
  "OpenAI": {
    "country": "US",
    "flag": "🇺🇸",
    "color": "from-emerald-500 to-teal-600",
    "badge": "bg-emerald-500/10 text-emerald-300 border-emerald-500/30"
  },
  "Poolside": {
    "country": "US",
    "flag": "🇺🇸",
    "color": "from-sky-400 to-cyan-500",
    "badge": "bg-sky-400/10 text-sky-300 border-sky-400/30"
  },
  "Sarvam AI": {
    "country": "IN",
    "flag": "🇮🇳",
    "color": "from-amber-500 to-orange-600",
    "badge": "bg-amber-600/10 text-amber-300 border-amber-600/30"
  },
  "StepFun": {
    "country": "CN",
    "flag": "🇨🇳",
    "color": "from-indigo-500 to-blue-600",
    "badge": "bg-indigo-500/10 text-indigo-400 border-indigo-500/30"
  },
  "Tencent": {
    "country": "CN",
    "flag": "🇨🇳",
    "color": "from-blue-500 to-teal-500",
    "badge": "bg-blue-500/10 text-blue-300 border-blue-500/30"
  },
  "Thinking Machines Lab": {
    "country": "US",
    "flag": "🇺🇸",
    "color": "from-fuchsia-500 to-purple-600",
    "badge": "bg-fuchsia-500/10 text-fuchsia-300 border-fuchsia-500/30"
  },
  "Upstage": {
    "country": "KR",
    "flag": "🇰🇷",
    "color": "from-amber-400 to-yellow-500",
    "badge": "bg-amber-400/10 text-amber-300 border-amber-400/30"
  },
  "Xiaomi": {
    "country": "CN",
    "flag": "🇨🇳",
    "color": "from-orange-500 to-amber-600",
    "badge": "bg-orange-500/10 text-orange-400 border-orange-500/30"
  },
  "Z.ai": {
    "country": "CN",
    "flag": "🇨🇳",
    "color": "from-rose-500 to-red-500",
    "badge": "bg-rose-500/10 text-rose-300 border-rose-500/30"
  },
  "xAI / SpaceXAI": {
    "country": "US",
    "flag": "🇺🇸",
    "color": "from-gray-300 to-slate-400",
    "badge": "bg-slate-400/10 text-slate-300 border-slate-400/30"
  },
  "LG AI Research": {
    "country": "KR",
    "flag": "🇰🇷",
    "color": "from-rose-500 to-red-600",
    "badge": "bg-rose-500/10 text-rose-300 border-rose-500/30"
  },
  "LG": {
    "country": "KR",
    "flag": "🇰🇷",
    "color": "from-rose-500 to-red-600",
    "badge": "bg-rose-500/10 text-rose-300 border-rose-500/30"
  },
  "SK Telecom": {
    "country": "KR",
    "flag": "🇰🇷",
    "color": "from-red-500 to-orange-500",
    "badge": "bg-red-500/10 text-red-300 border-red-500/30"
  },
  "SKT": {
    "country": "KR",
    "flag": "🇰🇷",
    "color": "from-red-500 to-orange-500",
    "badge": "bg-red-500/10 text-red-300 border-red-500/30"
  }
};

const SCOPE_DATA = {
  "period": "2026-01-01 ~ 2026-09-04",
  "scope": [
    "LLM (Large Language Models)",
    "MLLM / VLM / Omni foundation models"
  ],
  "excluded": [
    "image-generation-only models",
    "video-generation-only models (e.g. Seedance)",
    "OCR-only models",
    "ASR/TTS-only models",
    "embedding / reranker models",
    "reward / guard-only models",
    "simple quantized variants (FP8, NVFP4, INT4, GGUF, etc.)",
    "intermediate / base checkpoints unless representing distinct products"
  ]
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TIMELINE_DATA, COMPANY_META, SCOPE_DATA };
}
